### ISSUE TITLE
Update for KiCad 7

### ISSUE THREAD

**Issue by m3rkator** [ian-ross/kicad-plugins#12]
Hello Ian

Thanks for your wonderful plugin, which made my work so much easier in the past.

Unfortunately, it stopped working with KiCad 7

![grafik](https://user-images.githubusercontent.com/26457183/222258320-367c66dc-0274-4abf-b9e9-217293cd9731.png)

Screenshot inline.

Can you do something about it?

Bye
Holger

**Comment by ian-ross** [comment]
There's a KiCad 7?! That shows how up to date I am with KiCad... I had no idea there was even going to be a new version.

Let me see what I can do.

**Comment by ian-ross** [comment]
@m3rkator Do you think you could try the latest `SchematicPositionsToLayout.py`? I've made some updates for KiCad 7 that I think should do the trick. I've tested with a couple of my own projects, and it seems OK (including hierarchical sheets), but it's hard to be 100% confident. Thanks!

**Comment by m3rkator** [comment]
Hello  @ian-ross 

Same here. Update works with 100% of all my projects. But i can't speak for the rest of the globe.

For myself i can say: Awesome and many thanks.

Bye
Holger

**Comment by ian-ross** [comment]
Thanks for checking that out, @m3rkator !
