### ISSUE TITLE
Doesn't work with Kicad 7

### ISSUE THREAD

**Issue by Pkemarco** [ian-ross/kicad-plugins#13]
Hi guys and thank you for your hard work.
I tried recently to use this tool with Kicad 7 but I am getting this error :

![image](https://user-images.githubusercontent.com/30911289/225589567-8b7fcc95-3a5f-4150-bfb3-5fd29c3b5ec1.png)

Can you help me to fix it please ?
Thanks !

**Comment by ian-ross** [comment]
Interesting. I thought I'd got this working for KiCad 7 a couple of weeks ago, but it looks like I didn't deal with hierarchical sheets properly. (I thought I had...) I'll take a look later today. It should be a simple fix, I think.

**Comment by Pkemarco** [comment]
Ok, thanks !!

**Comment by ian-ross** [comment]
Give it a try now. I think I just fixed it. (Well, a very simple hierarchical sheets example now works anyway, and it didn't before...)

**Comment by Pkemarco** [comment]
It works now ! Thanks you !!!

**Comment by Pkemarco** [comment]
> Hi guys and thank you for your hard work. I tried recently to use this tool with Kicad 7 but I am getting this error :
> 
> ![image](https://user-images.githubusercontent.com/30911289/225589567-8b7fcc95-3a5f-4150-bfb3-5fd29c3b5ec1.png)
> 
> Can you help me to fix it please ? Thanks !
