### ISSUE TITLE
ratsnest is wrong！

### ISSUE THREAD

**Issue by HaydenHu** [ian-ross/kicad-plugins#6]
In kicad5.99, the ratsnest is not updated after running the plug-in！
The file must be saved and the ratsnest will not update correctly until the pcbnew is restarted.

![QQ20210928165930](https://user-images.githubusercontent.com/30103277/135059839-cb5ddb2b-f25d-438b-a889-d4ca4ae2a958.png)

@lvsoft 

Application: KiCad PCB 编辑器 (64-bit)

Version: (5.99.0-12597-g9f841da98e), release build

Libraries:
	wxWidgets 3.1.5
	libcurl/7.78.0-DEV Schannel zlib/1.2.11

Platform: Windows 10 (build 19043), 64-bit edition, 64 bit, Little endian, wxMSW

Build Info:
	Date: Sep 28 2021 00:32:52
	wxWidgets: 3.1.5 (wchar_t,wx containers)
	Boost: 1.76.0
	OCC: 7.5.0
	Curl: 7.78.0-DEV
	ngspice: 35
	Compiler: Visual C++ 1929 without C++ ABI

Build settings:
	KICAD_USE_OCC=ON
	KICAD_SPICE=ON

**Comment by HaydenHu** [comment]
Added this and solved it.
`pcbnew.Refresh()`

**Comment by alchemyyy** [comment]
this was true for me as well, thank you for the fix!

**Comment by ian-ross** [comment]
Fixed by #8 from @HaydenHu
